import Singularity.WalkBoundaryLaw
import Singularity.GreenPositive
import Mathlib.MeasureTheory.Measure.AbsolutelyContinuous

/-!
# Quasi-invariance from stationarity and semigroup generation

A positive-weight support element sends a stationary measure to an absolutely
continuous measure. This property propagates along permitted words. If those
words fill the group, all translates are equivalent to the original measure.
-/

noncomputable section
open MeasureTheory Set
open scoped ENNReal Classical

namespace Singularity

variable {Γ B : Type*} [Group Γ] [MeasurableSpace B] [MulAction Γ B]
    [MeasurableConstSMul Γ B]

omit [MeasurableConstSMul Γ B] in
/-- A single positive summand in the stationarity equation is dominated by the whole measure. -/
theorem stationary_jump_domination (s : Finset Γ) (μ : Γ → ℝ) (ν : Measure B)
    (hstat : ν = ∑ g : s, ENNReal.ofReal (μ g) • Measure.map (fun ξ : B => (g : Γ) • ξ) ν)
    (g : s) : ENNReal.ofReal (μ g) • Measure.map (fun ξ : B => (g : Γ) • ξ) ν ≤ ν := by
  nth_rw 2 [hstat]
  exact Finset.single_le_sum
    (f := fun a : s => ENNReal.ofReal (μ a) • Measure.map (fun ξ : B => (a : Γ) • ξ) ν)
    (fun _ _ t => by change (0 : ℝ≥0∞) ≤ _; exact bot_le) (Finset.mem_univ g)

omit [MeasurableConstSMul Γ B] in
/-- Positive support elements preserve the measure class in the forward direction. -/
theorem stationary_jump_absolutelyContinuous (s : Finset Γ) (μ : Γ → ℝ)
    (hpos : ∀ g ∈ s, 0 < μ g) (ν : Measure B)
    (hstat : ν = ∑ g : s, ENNReal.ofReal (μ g) • Measure.map (fun ξ : B => (g : Γ) • ξ) ν)
    (g : s) : Measure.map (fun ξ : B => (g : Γ) • ξ) ν ≪ ν :=
  (Measure.absolutelyContinuous_smul (ENNReal.ofReal_ne_zero_iff.mpr (hpos g g.property))).trans
    (Measure.absolutelyContinuous_of_le (stationary_jump_domination s μ ν hstat g))

/-- Every element generated by positive jumps sends ν to a measure absolutely continuous to ν. -/
theorem stationary_generated_absolutelyContinuous (s : Finset Γ) (μ : Γ → ℝ)
    (hpos : ∀ g ∈ s, 0 < μ g) (ν : Measure B)
    (hstat : ν = ∑ g : s, ENNReal.ofReal (μ g) • Measure.map (fun ξ : B => (g : Γ) • ξ) ν)
    {g : Γ} (hg : g ∈ Submonoid.closure (s : Set Γ)) :
    Measure.map (fun ξ : B => g • ξ) ν ≪ ν := by
  induction hg using Submonoid.closure_induction_left with
  | one =>
    simp only [one_smul]
    change Measure.map id ν ≪ ν
    rw [Measure.map_id]
  | mul_left a ha b _ ih =>
    have hi := ih.map (measurable_const_smul a)
    have hj := stationary_jump_absolutelyContinuous s μ hpos ν hstat ⟨a, ha⟩
    have he : Measure.map (fun ξ : B => a • ξ) (Measure.map (fun ξ : B => b • ξ) ν) =
        Measure.map (fun ξ : B => (a * b) • ξ) ν := by
      rw [Measure.map_map (measurable_const_smul a) (measurable_const_smul b)]
      congr 1
      funext ξ
      exact (mul_smul a b ξ).symm
    rw [he] at hi
    exact hi.trans hj

/-- Semigroup generation makes every group translate equivalent to the stationary measure. -/
theorem stationary_translate_equivalent (s : Finset Γ) (μ : Γ → ℝ)
    (hpos : ∀ g ∈ s, 0 < μ g) (hgen : Submonoid.closure (s : Set Γ) = ⊤)
    (ν : Measure B)
    (hstat : ν = ∑ g : s, ENNReal.ofReal (μ g) • Measure.map (fun ξ : B => (g : Γ) • ξ) ν)
    (g : Γ) : Measure.map (fun ξ : B => g • ξ) ν ≪ ν ∧
      ν ≪ Measure.map (fun ξ : B => g • ξ) ν := by
  have hall (a : Γ) : Measure.map (fun ξ : B => a • ξ) ν ≪ ν :=
    stationary_generated_absolutelyContinuous s μ hpos ν hstat (by rw [hgen]; trivial)
  refine ⟨hall g, ?_⟩
  have hi := (hall g⁻¹).map (measurable_const_smul g)
  rw [Measure.map_map (measurable_const_smul g) (measurable_const_smul g⁻¹)] at hi
  simp only [Function.comp_def, smul_inv_smul] at hi
  change Measure.map id ν ≪ _ at hi
  simpa only [Measure.map_id] using hi

end Singularity
