import Singularity.MaximalAtoms
import Singularity.StationaryQuasiInvariant
import Mathlib.MeasureTheory.Measure.Typeclasses.NullSingletonClass

/-!
# Stationary measures have no atoms when every orbit is infinite

A maximal atom must have maximal-mass predecessors under every positive jump.
Semigroup generation propagates this to the entire group orbit, contradicting
finiteness of the positive maximal-mass level set.
-/

noncomputable section
open MeasureTheory Set
open scoped Classical ENNReal

namespace Singularity

variable {Γ X : Type*} [Group Γ] [MeasurableSpace X] [MeasurableSingletonClass X]
  [MulAction Γ X] [MeasurableConstSMul Γ X]

/-- Stationarity gives the scalar convex-combination identity for singleton masses. -/
theorem stationary_atom_balance (s : Finset Γ) (μ : Γ → ℝ) (hμ : ∀ g ∈ s, 0 ≤ μ g)
    (ν : Measure X) [IsFiniteMeasure ν]
    (hstat : ν = ∑ g : s, ENNReal.ofReal (μ g) • Measure.map (fun x : X => (g : Γ) • x) ν)
    (x : X) : (ν {x}).toReal = ∑ g : s, μ g * (ν {(g : Γ)⁻¹ • x}).toReal := by
  have he : ν {x} = ∑ g : s, ENNReal.ofReal (μ g) * ν {(g : Γ)⁻¹ • x} := by
    nth_rw 1 [hstat]
    rw [Measure.finsetSum_apply]
    apply Finset.sum_congr rfl
    intro g _
    rw [Measure.smul_apply, Measure.map_apply (measurable_const_smul (g : Γ)) (measurableSet_singleton x)]
    change ENNReal.ofReal (μ g) * ν ((fun y : X => (g : Γ) • y) ⁻¹' {x}) = _
    congr 2
    ext y
    simp only [mem_preimage, mem_singleton_iff]
    constructor
    · intro h
      calc y = (g : Γ)⁻¹ • ((g : Γ) • y) := (inv_smul_smul _ _).symm
           _ = (g : Γ)⁻¹ • x := congrArg (fun z : X => (g : Γ)⁻¹ • z) h
    · rintro rfl
      exact smul_inv_smul _ _
  have hr := congrArg ENNReal.toReal he
  rw [ENNReal.toReal_sum (fun g _ => ENNReal.mul_ne_top ENNReal.ofReal_ne_top (measure_ne_top ν _))] at hr
  rw [hr]
  apply Finset.sum_congr rfl
  intro g _
  rw [ENNReal.toReal_mul, ENNReal.toReal_ofReal (hμ g g.property)]

/-- Every positive jump predecessor of a maximal atom is again maximal. -/
theorem stationary_maximal_atom_jump (s : Finset Γ) (μ : Γ → ℝ)
    (hpos : ∀ g ∈ s, 0 < μ g) (hmass : ∑ g ∈ s, μ g = 1)
    (ν : Measure X) [IsFiniteMeasure ν]
    (hstat : ν = ∑ g : s, ENNReal.ofReal (μ g) • Measure.map (fun x : X => (g : Γ) • x) ν)
    (M : ℝ) (hmax : ∀ y : X, (ν {y}).toReal ≤ M)
    (x : X) (hx : (ν {x}).toReal = M) (g : s) : (ν {(g : Γ)⁻¹ • x}).toReal = M := by
  have hmass' : ∑ a : s, μ a = 1 := by simpa only [Finset.sum_coe_sort] using hmass
  have hbal := stationary_atom_balance s μ (fun a ha => (hpos a ha).le) ν hstat x
  have hsum : ∑ a : s, μ a * (M - (ν {(a : Γ)⁻¹ • x}).toReal) = 0 := by
    simp_rw [mul_sub]
    rw [Finset.sum_sub_distrib, ← Finset.sum_mul, hmass', one_mul, ← hbal, hx, sub_self]
  have hnonneg (a : s) (_ : a ∈ (Finset.univ : Finset s)) :
      0 ≤ μ a * (M - (ν {(a : Γ)⁻¹ • x}).toReal) :=
    mul_nonneg (hpos a a.property).le (sub_nonneg.mpr (hmax _))
  have hzero := (Finset.sum_eq_zero_iff_of_nonneg hnonneg).mp hsum g (Finset.mem_univ g)
  exact (sub_eq_zero.mp ((mul_eq_zero.mp hzero).resolve_left (hpos g g.property).ne')).symm

/-- Maximality propagates through the semigroup generated by the support. -/
theorem stationary_maximal_atom_generated (s : Finset Γ) (μ : Γ → ℝ)
    (hpos : ∀ g ∈ s, 0 < μ g) (hmass : ∑ g ∈ s, μ g = 1)
    (ν : Measure X) [IsFiniteMeasure ν]
    (hstat : ν = ∑ g : s, ENNReal.ofReal (μ g) • Measure.map (fun x : X => (g : Γ) • x) ν)
    (M : ℝ) (hmax : ∀ y : X, (ν {y}).toReal ≤ M)
    {g : Γ} (hg : g ∈ Submonoid.closure (s : Set Γ)) :
    ∀ x : X, (ν {x}).toReal = M → (ν {g⁻¹ • x}).toReal = M := by
  induction hg using Submonoid.closure_induction_left with
  | one => simpa only [inv_one, one_smul] using (fun x (hx : (ν {x}).toReal = M) => hx)
  | mul_left a ha b _ ih =>
    intro x hx
    rw [mul_inv_rev, mul_smul]
    exact ih _ (stationary_maximal_atom_jump s μ hpos hmass ν hstat M hmax x hx ⟨a, ha⟩)

/-- A finite stationary measure has zero mass on every singleton if all group orbits are infinite. -/
theorem stationary_nullSingleton_of_infinite_orbits (s : Finset Γ) (μ : Γ → ℝ)
    (hpos : ∀ g ∈ s, 0 < μ g) (hmass : ∑ g ∈ s, μ g = 1)
    (hgen : Submonoid.closure (s : Set Γ) = ⊤)
    (ν : Measure X) [IsFiniteMeasure ν]
    (hstat : ν = ∑ g : s, ENNReal.ofReal (μ g) • Measure.map (fun x : X => (g : Γ) • x) ν)
    (horbit : ∀ x : X, (MulAction.orbit Γ x).Infinite) : NullSingletonClass ν := by
  constructor
  intro x
  by_contra hx
  obtain ⟨y, hy, hmax⟩ := exists_maximal_real_atom ν ⟨x, hx⟩
  have hfinite := finite_maximal_real_atoms ν y hy
  apply horbit y (hfinite.subset ?_)
  rintro z ⟨g, rfl⟩
  have hg : g⁻¹ ∈ Submonoid.closure (s : Set Γ) := by rw [hgen]; trivial
  simpa only [inv_inv, Set.mem_ofPred_eq] using
    stationary_maximal_atom_generated s μ hpos hmass ν hstat _ hmax hg y rfl

end Singularity
